### ISSUE TITLE
Making the "default" shade transparent.

### ISSUE THREAD

**Issue by tewen** [Rylern/InterpolateHeatmapLayer#1]
### Feature Request or Question

This video provides the detail of our inquiry: https://threadit.app/thread/hx9xgx7h8zf6ybwpak2q/message/ue4b3ysx7ghf6l7ufbq4eyfq?utm_medium=referral-link

Here are several of the images mentioned there:

![image](https://user-images.githubusercontent.com/346290/137213725-7ae5b998-9071-486b-b15e-c7460b049d58.png)

With the "roi" parameter:

![image](https://user-images.githubusercontent.com/346290/137213784-c0e0b671-167e-4e37-8e59-b0caa998b9f3.png)

Our original heatmap (the one we are replacing):

![image](https://user-images.githubusercontent.com/346290/137213833-ea144948-ceb9-40ee-b0f6-aae8d65b8d28.png)

That one uses [heatmap.js](https://github.com/pa7/heatmap.js), but we are a bit worried about the age of that library and the fact that it does not normally sit on top of MapBox. 

Thanks for your help! Great work so far.

**Comment by Rylern** [comment]
Hi, I can add an option to make the average color transparent (which is green is your example).
Here is an example of what it would look like:
![Screenshot from 2021-10-14 23-10-26](https://user-images.githubusercontent.com/60394504/137396017-4008bdf5-bd0b-4d17-95c5-ddc0720f953f.png)

Also since you don't have a lot of points I recommend you to set the `framebufferFactor` parameter to 1. This will remove the blurry effect on the gradient of color.

**Comment by tewen** [comment]
@Rylern much appreciated. I will run this by my colleague, but I think that is the direction we need.

**Comment by tewen** [comment]
@Rylern Just confirming that it would be transparent where no value is set? Correct?

**Comment by Rylern** [comment]
Not exactly, it's transparent where the computed value is more or less equal to the average of the points.
For example, if you have points with values [0, 0.5, 1], the average is 0.5, which corresponds to the green color, so by default, the map will be colored green. The solution I proposed would make here the green transparent, which means we couldn't see the point with value 0.5.

Making the color transparent when it is far from all points would require more work (and I'm not 100% sure it would be feasible with my solution), we would need to convert the position of a pixel to a world location. Right now I'm doing the inverse: I convert points locations to pixel positions. But I can take a look on it if you need to.

**Comment by tewen** [comment]
@Rylern Maybe start with the simple solution. If you put it in a branch, we can test quickly and provide some feedback.

**Comment by Rylern** [comment]
I created the [make-average-transparent](https://github.com/Rylern/InterpolateHeatmapLayer/tree/make-average-transparent) branch. With it, you can define a new parameter, `threshold`: if the distance between a value and the average (scaled between 0 and 1) is below the threshold, the associated color will be transparent.

For example, if you have `points` with values [0, 0.5, 1], and you create the layer with these parameters:
```
const layer = create({
    points: points
    threshold: 0.1
});
```
Then all points with values between 0.4 and 0.6 will be transparent.

`threshold` is a value between 0 and 1 even if the points take values outside that range, because the values and the average are scaled between 0 and 1 when computing their distance. It means that with the previous example, if we had `points` with values [0, 5, 10], then all points with values between 4 and 6 would be transparent.

**Comment by tewen** [comment]
@Rylern Thanks, we'll be testing this week. Much appreciated.

**Comment by Rylern** [comment]
The make-average-transparent branch has been merged to the main branch. I just changed the parameter name `threshold` to `averageThreshold`.
