### ISSUE TITLE
Trying to use InterpolateHeatmapLayer in place of Layer fails with  react-map-gl 

### ISSUE THREAD

**Issue by cscetbon** [Rylern/InterpolateHeatmapLayer#5]
In my react app I tried to replace
```
{data && (
  <Source type="geojson" data={data}>
    <Layer {...heatmapLayer} />
  </Source>
)}
```
by
```
{data && (
  <Source type="geojson" data={data}>
    <InterpolateHeatmapLayer {...heatmapLayer} />
  </Source>
)}
```

But get `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` Any idea what's going on here ? Is it because I can't use it the same way I do it today using [react-map-gl](https://github.com/visgl/react-map-gl) ? Any way I could ?

**Comment by Rylern** [comment]
I never used React so what I'm going to say might be wrong.

I think [react-map-gl](https://github.com/visgl/react-map-gl) is not compatible with InterpolateHeatmapLayer. Their `layer` object (see [here](https://visgl.github.io/react-map-gl/docs/api-reference/layer) and [here](https://github.com/visgl/react-map-gl/blob/7.1-release/src/components/layer.ts)) is different from the [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) `layer` object, from which InterpolateHeatmapLayer is based.

An alternative would be to use [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) instead of react-map-gl as explained in this [article](https://www.lostcreekdesigns.co/writing/introduction-to-mapbox-and-react/).

**Comment by cscetbon** [comment]
hmm, [react-map-gl](https://github.com/visgl/react-map-gl) is a wrapper around [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) so I can't see how it would be incompatible ... I think it's more than the object is not a React component and that I need to create one

**Comment by cscetbon** [comment]
It seems mapbox-gl uses also react under the hood so I don't have much to do. Closing this
