### ISSUE TITLE
Issues with style and question about colors

### ISSUE THREAD

**Issue by cscetbon** [Rylern/InterpolateHeatmapLayer#6]
Hey,

I'm using Mapbox with a style and it shows something like
<img width="768" alt="Screenshot 2023-12-13 at 7 21 28 PM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/b750cc73-0a03-494b-b8eb-da4c2bb05edc">
However when I use your code I get a different look even using the same style url

<img width="760" alt="Screenshot 2023-12-13 at 7 40 37 PM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/17869e96-40dd-4893-a336-e30c1e44b607">
Is it because the heatmap applies to the whole map instead of just the location where I have points ?

Also I'd like the colors to be inversed, meaning blue for high values and red for low values, is there a way to do it other than by manipulating the values myself to make low values high and high values low ?

**Comment by Rylern** [comment]
Hello,

About the different look: Yes, I think it's because the heatmap applies to the whole map. You have two options to fix this:
* Use the `pointRadius` parameter to only apply the heatmap around points. Something like `pointRadius: 500` should be enough.
* Use the `roi` parameter to only apply the heatmap in a specific area. Something like:
```javascript
roi: [{
  lat: 33.666166159172775,
  lon: -84.48114332974401
},
{
  lat: 33.666166159172775,
  lon: -84.3771437096422
},
{
  lat: 33.607548312648866,
  lon: -84.3771437096422
},
{
  lat: 33.607548312648866,
  lon: -84.48114332974401
}]
```
would cover your area.

About inversing the colors: you can use the `valueToColor` parameter. Something like:
```javascript
valueToColor: `
   vec3 valueToColor(float value) {
      return vec3(max((0.5-value)*2.0, 0.0), 1 - 2.0*abs(value - 0.5), max((value-0.5)*2.0, 0.0));
   }
`
```
(I just inversed the red and blue components of the default `valueToColor` function)

**Comment by cscetbon** [comment]
Thanks @Rylern I used the radius and it's way better and faster. Also knowing the range of my values I'm just inversing them. I'm now trying to find out if I can make it a bit faster but it seems to come from mapbox itself ... also I suppose if I create the map in advance it should be faster to just play with the layer, adding it and removing it right ?

**Comment by Rylern** [comment]
What do you mean by creating the map in advance?

There are two parameters you can use to make the map faster:
* `fasterPointRadius: true`
* `framebufferFactor: 0.1` (or any low value greater than 0)

However, they tend to reduce the visual quality.

**Comment by cscetbon** [comment]
> What do you mean by creating the map in advance?

I mean if I create it before loading the specific tab where I want it to appear

Also as you can see the rendering is blurry, is there any way to improve it ?

<img width="573" alt="Screenshot 2023-12-13 at 7 55 12 PM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/925d9526-b7d7-4a53-a2a5-9cb22cebb826">


<img width="475" alt="Screenshot 2023-12-13 at 7 55 27 PM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/54337e7b-d212-491c-bd84-a09976b40fcc">

**Comment by Rylern** [comment]
> I mean if I create it before loading the specific tab where I want it to appear

It depends on what you want to make faster. If you want to speed up the map initialization, yes you can do that. But if you want to speed up the rendering when the map is moved / zoomed in or out, you should use the parameters I mentionned.

> Also as you can see the rendering is blurry, is there any way to improve it ?

Can you try to set this parameter and see if it changes:
```
framebufferFactor: 1
```

**Comment by cscetbon** [comment]
Same, it's still blurry as you can see

<img width="489" alt="Screenshot 2023-12-15 at 3 54 44 PM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/e811dc0c-b763-4d35-bb36-459017c5fc31">

**Comment by Rylern** [comment]
Can I see your code calling the `interpolateHeatmapLayer.create()` function? It still looks pixelated (especially the red/green part).

This usually happens when the framebuffer factor is too low. For example, this layer has a framebuffer factor of 0.1:
![image](https://github.com/Rylern/InterpolateHeatmapLayer/assets/60394504/78022fbd-d1b3-479a-97e4-58c4daf98281)

And this one has a framebuffer factor of 1:
![image](https://github.com/Rylern/InterpolateHeatmapLayer/assets/60394504/5a4d9acf-50d5-4180-9e23-f08458b4abca)

**Comment by cscetbon** [comment]
[Here](https://pastebin.com/raw/RhkyfHHj) it is. I also tried with the style you use in your example and it's slightly different as you can. Also don't you think the glowing effect where I have my outliers is weird in the rendered picture ?

<img width="505" alt="Screenshot 2023-12-17 at 10 42 43 AM" src="https://github.com/Rylern/InterpolateHeatmapLayer/assets/2619840/75b6d7d2-d75a-494a-a550-ef4d118eecb2">

**Comment by Rylern** [comment]
I see, it's because the layer parameters are passed to the `map` and not to the `layer`.

You just have to change
```javascript
const layer = InterpolateHeatmapLayer.create({
            layerId: "mylayer",
            points: [...]
})
```

to
```javascript
const layer = interpolateHeatmapLayer.create({
        layerId: "mylayer",
        pointRadius: 500,
        framebufferFactor: 1,
        p: 3,
        points: [...]
})
```

and remove the `pointRadius` and `framebufferFactor` parameters from the map creation.

You see that I also added a `p` parameter. You might want to try different values for it as it changes the visualization. Higher values make the heatmap more sharp, like this (with `p=5`):
![image](https://github.com/Rylern/InterpolateHeatmapLayer/assets/60394504/41ae2247-d254-4ad4-bf38-62c701ec319f)

**Comment by cscetbon** [comment]
Thanks @Rylern closing this
